### ISSUE TITLE
Comprehensive Schema

### ISSUE THREAD

**Issue by stillinbeta** [tripit/api#232] opened 2019-03-28 17:26 UTC
One thing the API documentation is lacking is a comprehensive list of what objects have what fields. I would like to see what all possible members of every object type is, and whether those fields are mandatory or optional.

The ideal would be a machine-consumable format [like swagger](https://swagger.io/), but even an HTML table would be a huge improvement

**Comment by d-w-wilson-jr** [comment] 2019-04-01 15:40
This is a great idea and will be forwarded on as a recommendation.

**Comment by dave-symons** [comment] 2019-04-01 16:10
Closing as this is not a bug.

**Closed as completed by dave-symons** 2019-04-01 16:10 UTC
